<?php

namespace Server\PersonalBudget\Core\Database;

use Server\PersonalBudget\Core\Database\Drivers\ConnectionSQLite;

class DB extends ConnectionSQLite
{
    public function __construct($table)
    {
        parent::__construct($table);
    }

    public function insert($fields, $values): bool
    {
        return parent::insert($fields, $values); // TODO: Change the autogenerated stub
    }

    public function select(string $fields = '*', $where = null, $join = null, $order = null, $limit = null, bool $fetchAll = true): mixed
    {
        return parent::select($fields, $where, $join, $order, $limit, $fetchAll); // TODO: Change the autogenerated stub
    }

    public function update($where = null, array $fields = [], array $values = []): bool
    {
        return parent::update($where, $fields, $values); // TODO: Change the autogenerated stub
    }

    public function delete($where = null): bool
    {
        return parent::delete($where); // TODO: Change the autogenerated stub
    }
}